---
title: "COVID-19 Pandemic:"
author: "[Angus Watters](https://anguswg-ucsb.github.io/)"
subtitle: 'Data organization and analysis'
output:
  mikedown::ucsb:
    toc: TRUE
    number_sections: FALSE
    code_folding: "hide"
---

<br>


```{r, message = FALSE, warning = FALSE, echo = FALSE}
library(rmarkdown)     # You need this library to run this template.
library(mikedown) 
```

***

# **COVID-19 Pandemic** 


<br>
<br>
<br>


## ***California***

***

```{r, message= FALSE, warning = FALSE, echo = FALSE, out.width = "100%"}
# Libraries

library(tidyverse)
library(sf)
library(scales)
library(zoo)
library(plotly)
library(knitr)
library(kableExtra)
library(viridis)

pop = readxl::read_excel('../data/PopulationEstimates.xls', skip = 2) %>%
  select(state = State, pop_19 = POP_ESTIMATE_2019, fips = FIPStxt)

covid_url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'
covid = read_csv(covid_url)

tmp_state = 'California'
shp = USAboundaries::us_states() %>%
  filter(name == tmp_state)

# Question 1:

covid = inner_join(covid, select(pop, pop_19, fips), by = 'fips')

ca_covid = covid %>% filter(state == tmp_state) %>%
  group_by(county) %>%
  mutate(new_cases = cases - lag(cases)) %>%
  mutate(cases_per_cap = cases/pop_19, new_cases_per_cap = new_cases/pop_19)

counties = USAboundaries::us_counties() %>%
  filter(state_name == tmp_state)

# CASES PER 100,000 RESIDENTS
cases_per_100k = ca_covid %>%
  filter(date > max(date) - 7) %>%
  group_by(county, pop_19) %>%
  mutate(cases_100k = new_cases / (pop_19 / 100000)) %>%
  mutate(cases_100k = (sum(cases_100k)/(7))) %>%
  mutate(state = 'CA')

# 7 - DAY ROLLING MEAN
ca_covid = ca_covid %>%
  group_by(county, date) %>%
  mutate(total_cases = sum(cases, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(county) %>%
  mutate(new_cases = cases - lag(cases),
         rolling_mean = rollmean(new_cases, 7, fill = NA, align = 'right'))

# 7 - DAY ROLLING MEAN PER CAPITA
ca_covid  = ca_covid %>%
  group_by(county, date) %>%
  mutate(pop_19 = sum(pop_19)) %>%
  ungroup() %>%
  group_by(county) %>%
  mutate(rolling_mean_per_cap = rollmean(new_cases_per_cap, 7, fill = NA, align = 'right'))

covid_tmp = covid %>%
  filter(state == tmp_state) %>%
  group_by(county) %>%
  mutate(new_cases = cases - lag(cases)) %>%
  mutate(cases_per_cap = cases/pop_19, new_cases_per_cap = new_cases/pop_19)
ca_rolling = covid_tmp %>%
  group_by(state, date) %>%
  summarise(cases = sum(cases, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(state) %>%
  mutate(new_cases = cases - lag(cases),
         rolling_mean = rollmean(new_cases, 7, fill = NA, align = 'right'))
  # filter(new_cases >= 0)
```



### **Risk level criteria**

***


#### In hopes of reducing the spread of COVID-19, the California government has created a tier based classification system for counties. The tiers are based on an adjusted case rate of the number of new cases per 100,000 residents over a 7-day period. 

<br>

```{r, message= FALSE, warning = FALSE, echo = FALSE, out.width=1200 }

# COUNTY LOCKDOWN STATUS
# CRITERIA:
# Widespread ----- daily new cases per 100k >= 7.0
# Substantial ----- 7.0 > daily new cases per 100k >= 4.0
# Moderate ----- 3.9 >= daily new cases per 100k >= 1.0
# Minimal ----- 1.0 > daily new cases per 100kk

criteria = data.frame(risk_level = c('Widespread', 'Substantial', 'Moderate', 'Minimal'),
                      daily_new_cases_100k = c('> 7.0', '6.9 - 4.0', '3.9 - 1.0', '1.0 >') )

criteria[2] <- cell_spec(criteria[[2]], color = "white", bold = T,
    background = spec_color(1:4, end = 0.9, option = "D", direction = 1))

kbl(criteria, col.names = c('Risk level', 'Daily new cases per 100,000 residents'), escape = F, align = "c") %>%
  kable_material(c("striped", "hover")) %>% 
  kable_styling(position = "center")
```

<br>
<br>

```{r, message= FALSE, warning = FALSE, echo = FALSE, out.width = "100%"}
# CREATE DATAFRAME FOR CA COUNTIES + GEOMETRIES
ca_spatial = ca_covid %>%
  group_by(county) %>%
  arrange(desc(date)) %>%
  slice(n = 1)

other_names = c('Oregon', 'Nevada', 'Arizona')

other_states = USAboundaries::us_states() %>% 
  filter(name %in% other_names)

# SELECT DESIRED COLUMNS FROM COUNTIES SF DATAFRAME

counties = counties %>% select(state = state_name, county = name, fips = geoid)
# counties = counties %>% select(state, county, fips)

# JOIN DATAFRAME OF 58 COUNTIES W/ RESPECTIVE GEOMETRIES
ca_spatial = left_join(ca_spatial, select(counties, fips), by = 'fips') %>%
  st_as_sf()

temp7 = cases_per_100k %>% group_by(county) %>%
  arrange(desc(date)) %>%
  slice(n =1)

ca_spatial = left_join(ca_spatial, select(temp7, county, cases_100k), by = 'county')

font = list(
  family = 'Courier',
  size = 15,
  color = 'white')
label = list(
  bgcolor = '#232F34',
  bordercolor = 'transparent',
  font = font)

gg_cases_per_100 = ggplot() +
  geom_sf(data = shp) +
  geom_sf(data = ca_spatial, aes(fill = cases_100k,
                                 text = paste0('', cases_100k),
                                 text2 = county),
          col = 'black', size = .3) +
  viridis::scale_fill_viridis(discrete = FALSE, option = "D") +
  labs(title = "Adjusted case rate",
       fill = 'Cases per 100,000 residents') +
    theme(axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(face = "bold", size = 16),
        axis.title.y = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.title = element_text(face = 'bold', size = 20),
        plot.subtitle = element_text(size = 14),
        legend.title = element_text(face = "bold", size = 16, hjust = 0.5),
        legend.title.align = 0.5,
        legend.text = element_text(face = "bold", size = 12))

plotly_cases100k = ggplotly(gg_cases_per_100, 
                            height = 800, width = 1200, 
                            tooltip = c('text2', 'text')) %>%
  style(hoverlabel = label) %>%
  layout(font = font)


plotly_cases100k


```


<br>
<br>
<br>

```{r, message= FALSE, warning = FALSE, echo = FALSE, out.width = "100%"}
tmp1 = ca_spatial %>% mutate(Tier = case_when(cases_100k >= 7.0 ~ 'Widespread',
                                                7.0 > cases_100k & cases_100k >= 4.0 ~ 'Substantial',
                                                3.9 > cases_100k & cases_100k >= 1.0 ~ 'Moderate',
                                                1.0 > cases_100k ~ 'Minimal')) %>% 
  mutate(Tier = as.factor(Tier))

# RColorBrewer::display.brewer.all(n=4, exact.n=FALSE)
# col3 = viridis::viridis_pal()
# col4 = RColorBrewer::brewer.pal(9,"Viridis")
# pals3 = leaflet::colorBin(col3, domain = 1:4)

# COLOR EXAMPLE:

# dat <- data.frame(x=runif(10),y=runif(10),
#         grp = rep(LETTERS[1:5],each = 2),stringsAsFactors = TRUE)
# library(RColorBrewer)
# myColors <- brewer.pal(4,"YlOrRd")
# names(myColors) <- levels(tmp1$status)
# colScale <- scale_fill_manual(name = "status",values = myColors)

gg_lockdown = ggplot() +
  geom_sf(data = shp) +
  geom_sf(data = tmp1, aes(fill = Tier, text = paste0('County: ', county)), 
                           col = 'black', size = .3) +
  viridis::scale_fill_viridis(discrete = TRUE, option = "D") +
  labs(fill = 'Tier',
       title = "County risk levels") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(face = "bold", size = 16),
        axis.title.y = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.title = element_text(face = 'bold', size = 20),
        plot.subtitle = element_text(size = 14),
        legend.title = element_text(face = "bold", size = 16, hjust = 0.5),
        legend.title.align = 0.5,
        legend.text = element_text(face = "bold", size = 12))

plotly_lockdown = ggplotly(gg_lockdown,
                           tooltip = c('Tier', 'text'),
                           height = 800, width = 1000) %>%
  style(hoverlabel = label) %>%
  layout(font = font,
         yaxis = list(fixedrange = TRUE)) %>% 
    config(displayModeBar = FALSE)

plotly_lockdown
```

<br>
<br>
<br>

### **Daily new cases**

***

<br>

```{r, message= FALSE, warning = FALSE, echo = FALSE, out.width = "100%"}
# CA STATE ROLLING MEAN GRAPH
gg_ca_roll_mean = ggplot(data = ca_rolling, aes(x = date, y = new_cases)) +
  geom_col(aes(y = new_cases), col = 'cornflowerblue', fill = 'cyan4', stat = 'identity') +
  geom_line(aes(y = rolling_mean), col = 'darkblue', size = 1) +
  labs(title = '7-day rolling mean',
       x = 'Date',
       y = 'New cases',
       subtitle = 'Data Source: The New York Times') +
  theme(axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(face = "bold", size = 16),
        axis.title.y = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.title = element_text(face = 'bold', size = 20),
        plot.subtitle = element_text(size = 14),
        legend.title = element_text(face = "bold", size = 16, hjust = 0.5),
        legend.title.align = 0.5,
        legend.text = element_text(face = "bold", size = 12))

plot_ca_roll = ggplotly(gg_ca_roll_mean, height = 800, width = 1400) %>%
  style(hoverlabel = label) %>%
  layout(font = font,
         yaxis = list(fixedrange = TRUE)) %>% 
    config(displayModeBar = FALSE)

plot_ca_roll
```

<br>
<br>
<br>
<br>
<br>
<br>

### **County level**

*** 

```{r, message= FALSE, warning = FALSE, echo = FALSE, out.width = "100%"}
# COUNTY ROLLING MEAN PER CAPITA PLOT
tmp2 = ca_covid %>% filter(new_cases >= 0) %>% rename('Rolling mean per capita' = rolling_mean_per_cap, County = county, Date = date)

gg_county_rolling = ggplot(data = tmp2, aes(x= Date, y = `Rolling mean per capita`)) +
  geom_line(aes(col = County), size = .5) +
  scale_color_viridis_d(direction = -1) +
  labs(title = '7-day rolling mean per capita',
       x = 'Date',
       y = 'New cases per capita',
       col = 'County',
       subtitle = 'Data Source: The New York Times') +
  theme(axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(face = "bold", size = 16),
        axis.title.y = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.title = element_text(face = 'bold', size = 20),
        plot.subtitle = element_text(size = 14),
        legend.title = element_text(face = "bold", size = 16, hjust = 0.5),
        legend.title.align = 0.5,
        legend.text = element_text(face = "bold", size = 12),
        legend.position = "bottom")
plot_county_rolling = ggplotly(gg_county_rolling, 
                               height = 700, width = 1400,
                               tooltip = c('y', 'County', 'x')) %>%
  style(hoverlabel = label) %>%
  layout(font = font,
         yaxis = list(fixedrange = TRUE)) %>% 
    config(displayModeBar = FALSE)

plot_county_rolling

```

<br>
<br>
<br>
<br>
<br>
<br>

### **Southern California**

*** 

```{r, message= FALSE, warning = FALSE, echo = FALSE, out.width = "100%"}
# SO CAL ROLLING MEAN PER CAPITA PLOTS
so_cal_counties = c('Los Angeles', 'Orange', 'San Diego', 'San Luis Obispo', 'Santa Barbara', 'Ventura')
so_cal = ca_covid %>% filter(county %in% so_cal_counties)
so_cal$county = factor(so_cal$county,levels=c('San Luis Obispo', 'Santa Barbara',
                                               'Ventura', 'Los Angeles', 'Orange', 'San Diego'))

gg_so_cal_roll_mean = ggplot(data = so_cal, aes(x = date, y = rolling_mean_per_cap)) +
  geom_col(aes(y = rolling_mean_per_cap), col = 'cornflowerblue', fill = 'cyan4', stat = 'identity') +
  geom_line(aes(y = rolling_mean_per_cap), col = 'darkblue', size = 0.5) +
  labs(title = 'Daily new cases',
       x = 'Date',
       y = 'New cases',
       subtitle = 'Data Source: The New York Times') +
  theme(axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(face = "bold", size = 16),
        axis.title.y = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.title = element_text(face = 'bold', size = 22),
        plot.subtitle = element_text(size = 14),
        legend.title = element_text(face = "bold", size = 16, hjust = 0.5),
        legend.title.align = 0.5,
        legend.text = element_text(face = "bold", size = 12),
        strip.text = element_text(face = 'bold', size=16)) +
  facet_wrap(~county) +
  scale_y_continuous(labels = scales::comma)
# height = 1000, width = 1200,
plot_so_cal_roll_mean = ggplotly(gg_so_cal_roll_mean, height = 1000, width = 1400) %>%
  style(hoverlabel = label) %>%
  layout(font = font, 
         yaxis = list(fixedrange = TRUE)) %>% 
    config(displayModeBar = FALSE)

plot_so_cal_roll_mean
```




































